In [19]:
# get specific item from array [row, column]
import numpy as np
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

print(a)

print(a[1,5]) # row 1 as starting is 0

print(a[1,-2]) # working from backwards as in a list

print(a[0,:]) # get all the rows

print(a[ :, 2 ]) # get any specific column

print(a[0, 1:6:2]) # start index:end index:stepsize

print(a[1, 0:-1:2]) # start index:end index:stepsize

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]
[ 8 10 12]


In [23]:
#change element in array
a[1,5] = 20
print(a)

a[: ,2] = 5 #change a specific column with one value
print(a)

a[:, 2] = [1,2] #change a specific column with sub array
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [31]:
# 3D examples
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

print(b[0,1,1]) # getting specific value inside 3D array

print(b[1,1,:]) #get to the second array, get second row and print all

print(b[:, 1, :]) #print row#1 from each element of array


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[7 8]
[[3 4]
 [7 8]]


In [35]:
# 3d replace
b[:,1,:] = ([[5,5], [5,5]])
print(b)

[[[1 2]
  [5 5]]

 [[5 6]
  [5 5]]]
