In [63]:
# all zero matrix
import numpy as np
# print(np.zeros(5)) #vector of 5
#
# # print(np.zeros((2,3))) # 2 dim

print(np.zeros((3,3,3))) # 3 dim
#
# print(np.zeros((2,3,3,2))) # 4 dimension

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [64]:
# all 1s matrix
print(np.ones((1,2)))
print(np.ones((3,3)))

[[1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [66]:
#any other number
print(np.full((2,2), 5)) #shape,number
print(np.full((3,3), 0))

[[5 5]
 [5 5]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
#any other number any can use some other array shape
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(np.full_like(a, 4))
print(np.full(a.shape, 4))

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [24]:
#random decimal numbers
np.random.rand(2,4, 3)
np.random.random_sample(a.shape) #same shape as other array

array([[0.45456027, 0.46200563, 0.26782779, 0.86832786, 0.50206966,
        0.74851703, 0.04682557],
       [0.207275  , 0.97312074, 0.11071406, 0.38203402, 0.78544246,
        0.27385143, 0.44070408]])

In [69]:
# random integer values
np.random.randint(4, size = (2,2)) # 4 is start value
np.random.randint(4,7, size = (2,2)) # 4 is start value and 7 is end
np.random.randint(-4,7, size = (2,2)) # -4 is start value and 7 is end
np.random.randint(0,19, size = (3,3))

array([[18, 14, 13],
       [15,  1, 18],
       [15, 15, 11]])

In [71]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,5,axis = 0) #5 defines how many times it has to repat
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [80]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z
print('first')
print(output)
output[1:-1,1:-1] = z
print('second')
print(output)

first
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
second
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
# be careful when copying arrays
a = [1,2,3]
b = a
b[0] = 100
print(b)
# this okay
print(a)
# value of a is also changed
# so if you copying then

b = a.copy()
b[0] = 200
print(b)
print(a) # original values of a are retained

[100, 2, 3]
[100, 2, 3]
[200, 2, 3]
[100, 2, 3]
