In [12]:
# all zero matrix
import numpy as np
print(np.zeros(5)) #vector of 5

print(np.zeros((2,3))) # 2 dim

print(np.zeros((1,2,3))) # 3 dim

print(np.zeros((2,3,3,2))) # 4 dimension

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]]
[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [14]:
# all 1s matrix
print(np.ones((1,2)))

[[1. 1.]]


In [15]:
#any other number
print(np.full((2,2), 5)) #shape,number

[[5 5]
 [5 5]]


In [21]:
#any other number any can use some other array shape
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(np.full_like(a, 4))
print(np.full(a.shape, 4))

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [24]:
#random decimal numbers
np.random.rand(2,4, 3)
np.random.random_sample(a.shape) #same shape as other array

array([[0.45456027, 0.46200563, 0.26782779, 0.86832786, 0.50206966,
        0.74851703, 0.04682557],
       [0.207275  , 0.97312074, 0.11071406, 0.38203402, 0.78544246,
        0.27385143, 0.44070408]])

In [55]:
# random interger values
np.random.randint(4, size = (2,2)) # 4 is start value
np.random.randint(4,7, size = (2,2)) # 4 is start value and 7 is end
np.random.randint(-4,7, size = (2,2)) # -4 is start value and 7 is end

array([[ 2,  6],
       [ 4, -2]])

In [56]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,5,axis = 0) #5 defines how many times it has to repat
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
