In [4]:
import time
start = time.time()

a = [i for i in range(100000000)]

print(time.time() - start)


12.982117891311646


In [7]:
import numpy as np
import time
start = time.time()

a = np.arange(100000000)

print(time.time() - start)

9.969877004623413


In [10]:
# one dimensional and multiplication
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b)
print(a)

[ 4 10 18]
[1 2 3]


In [12]:
# 2 dimensional array
import numpy as np
b = np.array([[9.0, 8.1, 5.3], [1.1,2.4,5.6]])
print(b)


[[9.  8.1 5.3]
 [1.1 2.4 5.6]]


In [15]:
#get dimensions
b.ndim

2

In [17]:
# get shape
a.shape
b.shape

(2, 3)

In [20]:
# get type
a.dtype
b.dtype

dtype('float64')

In [22]:
# get size
a.itemsize
b.itemsize

8

In [24]:
# total size
a.size
b.size

6