In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
# maths
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a**2)
b = np.array([1,1,1,1])
print(a+b)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[2 3 4 5]


In [10]:
#take sin of all values
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
