In [12]:
#load data from file
import numpy as np
filedata = np.genfromtxt('data.txt', delimiter=',')
print(filedata)
# created all values be default as float


#convert it to integer
print(filedata.astype('int32'))


[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [13]:
# Boolean masking and advanced indexing
filedata > 50 # get true and false where values in fildata > 50


array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [14]:
# get the values greater than 50
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [17]:
#index with a list
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,5]] # getting values for index defined in the list



array([2, 4, 6])

In [20]:
# if we look downrards (1,3,1) then (13,42,22) and so on is there any value > 50
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [21]:
# if we look downrards (1,3,1) then (13,42,22) and so on is all value > 50
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [22]:
((filedata >50) & (filedata < 10))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [23]:
(~(filedata >50) & (filedata < 10))

array([[ True, False, False, False, False, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False, False, False, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True, False, False],
       [ True, False, False, False, False, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])