In [9]:
import numpy as np
before = np.array([[1,2,3,4], [4,5,6,6]])
print(before)
print(before.shape)

# reshape array till the time the same amount of total values are there/ values have to fit in
after = before.reshape((8,1))
print(after)

print(before.reshape((4,2)))

print(before.reshape((2,2,2)))

[[1 2 3 4]
 [4 5 6 6]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [4]
 [5]
 [6]
 [6]]
[[1 2]
 [3 4]
 [4 5]
 [6 6]]
[[[1 2]
  [3 4]]

 [[4 5]
  [6 6]]]


In [11]:
#vertically stacking vectors (sizes have to match)
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2]) # one copy of v1 above v2
np.vstack([v1,v2,v2,v2]) # one copy of v1 and 3 copies of v2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [16]:
#horizontal stacks
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.hstack((v1,v2))

h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])