https://www.hackerrank.com/challenges/np-shape-reshape/problem?isFullScreen=true

In [2]:
import numpy

my__1D_array = numpy.array([1, 2, 3, 4, 5])
print(my__1D_array.shape) # 1 row and 5 column
my__2D_array = numpy.array([[1, 2],[3, 4],[6,5]])
print(my__2D_array.shape) # 3 rows and 2 column

(5,)
(3, 2)


In [9]:
# (b). Using shape to change array dimensions


change_array = numpy.array([1,2,3,4,5,6])
change_array.shape = (2, 3)
print(change_array)

[[1 2 3]
 [4 5 6]]


In [12]:
# reshape : The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.#

my_array = numpy.array([1,2,3,4,5,6])
print('reshape')
print(numpy.reshape(my_array,(3,2)))
print('og')
print(my_array)


reshape
[[1 2]
 [3 4]
 [5 6]]
og
[1 2 3 4 5 6]


In [22]:
arr = list(map(int, input().strip().split()))
#important to convert to integer else the output will be like ['1', '2', '3', '4', '5', '6', '7', '8', '9']
my_array = numpy.array((arr))
print(my_array.reshape(3,3))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
