https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem?isFullScreen=true

In [5]:
# We can generate the transposition of an array using the tool numpy.transpose.
# It will not affect the original array, but it will create a new array.#

import numpy
my_array = numpy.array([[1,2,3], [4,5,6]])
print(my_array)
print('transposed')
print(numpy.transpose(my_array))

my_array2 = numpy.array([[1,3], [4,6]])
print(numpy.transpose(my_array2))

[[1 2 3]
 [4 5 6]]
transposed
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [3 6]]


In [4]:
# Flatten The tool flatten creates a copy of the input array flattened to one dimension.

import numpy
my_array = numpy.array([[1,2,3], [4,5,6]])
print(my_array.flatten())

[1 2 3 4 5 6]


In [24]:
n, m  = map(int, input().split())
matrix = []
for _ in range(n):
    row = list(map(int, input().split()))
    matrix.append(row)
my_list = numpy.array((matrix))

print(numpy.transpose(matrix))
print(matrix)
print(my_list.flatten())



[[1 4]
 [3 6]]
[[1, 3], [4, 6]]
[1 3 4 6]
